config/routes.rb
Rails.application.routes.draw do
  get 'page/index'
  resources :concessionaria
  resources :conscesionaria
  resources :clientes
  resources :carros
  root to: "page#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/concessionaria_controller.rb
class ConcessionariaController < ApplicationController
  before_action :set_concessionarium, only: %i[ show edit update destroy ]

  # GET /concessionaria or /concessionaria.json
  def index
    @concessionaria = Concessionarium.all
  end

  # GET /concessionaria/1 or /concessionaria/1.json
  def show
  end

  # GET /concessionaria/new
  def new
    @concessionarium = Concessionarium.new
  end

  # GET /concessionaria/1/edit
  def edit
  end

  # POST /concessionaria or /concessionaria.json
  def create
    @concessionarium = Concessionarium.new(concessionarium_params)

    respond_to do |format|
      if @concessionarium.save
        format.html { redirect_to @concessionarium, notice: "Concessionarium was successfully created." }
        format.json { render :show, status: :created, location: @concessionarium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concessionarium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concessionaria/1 or /concessionaria/1.json
  def update
    respond_to do |format|
      if @concessionarium.update(concessionarium_params)
        format.html { redirect_to @concessionarium, notice: "Concessionarium was successfully updated." }
        format.json { render :show, status: :ok, location: @concessionarium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concessionarium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concessionaria/1 or /concessionaria/1.json
  def destroy
    @concessionarium.destroy
    respond_to do |format|
      format.html { redirect_to concessionaria_url, notice: "Concessionarium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concessionarium
      @concessionarium = Concessionarium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concessionarium_params
      params.require(:concessionarium).permit(:nome, :cidade, :endereco, :anos_de_mercado)
    end
end

app/helpers/concessionaria_helper.rb
module ConcessionariaHelper
end

app/views/concessionaria/_form.html.erb
<%= form_with(model: concessionarium) do |form| %>
  <% if concessionarium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concessionarium.errors.count, "error") %> prohibited this concessionarium from being saved:</h2>

      <ul>
        <% concessionarium.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :anos_de_mercado %>
    <%= form.text_field :anos_de_mercado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concessionaria/edit.html.erb
<h1>Editing Concessionarium</h1>

<%= render 'form', concessionarium: @concessionarium %>

<%= link_to 'Show', @concessionarium %> |
<%= link_to 'Back', concessionaria_path %>

app/views/concessionaria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concessionaria</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cidade</th>
      <th>Endereco</th>
      <th>Anos de mercado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concessionaria.each do |concessionarium| %>
      <tr>
        <td><%= concessionarium.nome %></td>
        <td><%= concessionarium.cidade %></td>
        <td><%= concessionarium.endereco %></td>
        <td><%= concessionarium.anos_de_mercado %></td>
        <td><%= link_to 'Show', concessionarium, class: "bt-info bt" %></td>
        <td><%= link_to 'Edit', edit_concessionarium_path(concessionarium), class: "bt-blue bt" %></td>
        <td><%= link_to 'Destroy', concessionarium, class: "bt-red bt", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'nova concessionaria', new_concessionarium_path, class: "bt-green" %>

app/views/concessionaria/new.html.erb
<h1>New Concessionarium</h1>

<%= render 'form', concessionarium: @concessionarium %>

<%= link_to 'Back', concessionaria_path %>

app/views/concessionaria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @concessionarium.nome %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @concessionarium.cidade %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @concessionarium.endereco %>
</p>

<p>
  <strong>Anos de mercado:</strong>
  <%= @concessionarium.anos_de_mercado %>
</p>

<%= link_to 'Edit', edit_concessionarium_path(@concessionarium) %> |
<%= link_to 'Back', concessionaria_path %>