config/routes.rb
Rails.application.routes.draw do
  get 'page/index'
  resources :concessionaria
  resources :conscesionaria
  resources :clientes
  resources :carros
  root to: "page#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/conscesionaria_controller.rb
class ConscesionariaController < ApplicationController
  before_action :set_conscesionarium, only: %i[ show edit update destroy ]

  # GET /conscesionaria or /conscesionaria.json
  def index
    @conscesionaria = Conscesionarium.all
  end

  # GET /conscesionaria/1 or /conscesionaria/1.json
  def show
  end

  # GET /conscesionaria/new
  def new
    @conscesionarium = Conscesionarium.new
  end

  # GET /conscesionaria/1/edit
  def edit
  end

  # POST /conscesionaria or /conscesionaria.json
  def create
    @conscesionarium = Conscesionarium.new(conscesionarium_params)

    respond_to do |format|
      if @conscesionarium.save
        format.html { redirect_to @conscesionarium, notice: "Conscesionarium was successfully created." }
        format.json { render :show, status: :created, location: @conscesionarium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conscesionarium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conscesionaria/1 or /conscesionaria/1.json
  def update
    respond_to do |format|
      if @conscesionarium.update(conscesionarium_params)
        format.html { redirect_to @conscesionarium, notice: "Conscesionarium was successfully updated." }
        format.json { render :show, status: :ok, location: @conscesionarium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conscesionarium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conscesionaria/1 or /conscesionaria/1.json
  def destroy
    @conscesionarium.destroy
    respond_to do |format|
      format.html { redirect_to conscesionaria_url, notice: "Conscesionarium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conscesionarium
      @conscesionarium = Conscesionarium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conscesionarium_params
      params.require(:conscesionarium).permit(:nome, :cidade, :endereco, :anos_de_mercado)
    end
end

app/helpers/conscesionaria_helper.rb
module ConscesionariaHelper
end

app/views/conscesionaria/_form.html.erb
<%= form_with(model: conscesionarium) do |form| %>
  <% if conscesionarium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conscesionarium.errors.count, "error") %> prohibited this conscesionarium from being saved:</h2>

      <ul>
        <% conscesionarium.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :anos_de_mercado %>
    <%= form.text_field :anos_de_mercado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conscesionaria/edit.html.erb
<h1>Editing Conscesionarium</h1>

<%= render 'form', conscesionarium: @conscesionarium %>

<%= link_to 'Show', @conscesionarium %> |
<%= link_to 'Back', conscesionaria_path %>

app/views/conscesionaria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conscesionaria</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cidade</th>
      <th>Endereco</th>
      <th>Anos de mercado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conscesionaria.each do |conscesionarium| %>
      <tr>
        <td><%= conscesionarium.nome %></td>
        <td><%= conscesionarium.cidade %></td>
        <td><%= conscesionarium.endereco %></td>
        <td><%= conscesionarium.anos_de_mercado %></td>
        <td><%= link_to 'Show', conscesionarium %></td>
        <td><%= link_to 'Edit', edit_conscesionarium_path(conscesionarium) %></td>
        <td><%= link_to 'Destroy', conscesionarium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conscesionarium', new_conscesionarium_path %>

app/views/conscesionaria/new.html.erb
<h1>New Conscesionarium</h1>

<%= render 'form', conscesionarium: @conscesionarium %>

<%= link_to 'Back', conscesionaria_path %>

app/views/conscesionaria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @conscesionarium.nome %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @conscesionarium.cidade %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @conscesionarium.endereco %>
</p>

<p>
  <strong>Anos de mercado:</strong>
  <%= @conscesionarium.anos_de_mercado %>
</p>

<%= link_to 'Edit', edit_conscesionarium_path(@conscesionarium) %> |
<%= link_to 'Back', conscesionaria_path %>