config/routes.rb
Rails.application.routes.draw do
  get 'page/index'
  resources :concessionaria
  resources :conscesionaria
  resources :clientes
  resources :carros
  root to: "page#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/carro.rb
class Carro < ApplicationRecord
    
belongs_to :cliente

end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: %i[ show edit update destroy ]

  # GET /carros or /carros.json
  def index
    @carros = Carro.all
  end

  # GET /carros/1 or /carros/1.json
  def show
  end

  # GET /carros/new
  def new
    @carro = Carro.new
  end

  # GET /carros/1/edit
  def edit
  end

  # POST /carros or /carros.json
  def create
    @carro = Carro.new(carro_params)

    respond_to do |format|
      if @carro.save
        format.html { redirect_to @carro, notice: "Carro was successfully created." }
        format.json { render :show, status: :created, location: @carro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carros/1 or /carros/1.json
  def update
    respond_to do |format|
      if @carro.update(carro_params)
        format.html { redirect_to @carro, notice: "Carro was successfully updated." }
        format.json { render :show, status: :ok, location: @carro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1 or /carros/1.json
  def destroy
    @carro.destroy
    respond_to do |format|
      format.html { redirect_to carros_url, notice: "Carro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carro
      @carro = Carro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def carro_params
      params.require(:carro).permit(:placa, :modelo, :chassi, :ano, :cliente_id)
    end
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/views/carros/_form.html.erb
<%= form_with(model: carro) do |form| %>
  <% if carro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
        <% carro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :placa %>
    <%= form.text_field :placa %>
  </div>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo %>
  </div>

  <div class="field">
    <%= form.label :chassi %>
    <%= form.text_field :chassi %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano %>
  </div>

  <div class="field">
    <%= form.label :cliente %>
    <%= form.select :cliente_id, Cliente.all.map{ |l| [l.nome, l.id] }, {:include_blank => 'Selecione o cliente'} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/carros/edit.html.erb
<h1>Editing Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Show', @carro %> |
<%= link_to 'Back', carros_path %>

app/views/carros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carros</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Placa</th>
      <th>Modelo</th>
      <th>Chassi</th>
      <th>Ano</th>
      <th>cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carros.each do |carro| %>
      <tr>
        <td><%= carro.id %></td>
        <td><%= carro.placa %></td>
        <td><%= carro.modelo %></td>
        <td><%= carro.chassi %></td>
        <td><%= carro.ano %></td>
        <td><%= carro.try(:cliente).try(:nome) %></td>
        <td><%= link_to 'detalhes', carro, class: "bt-info bt" %></td>
        <td><%= link_to 'Editar', edit_carro_path(carro), class: "bt-blue bt" %></td>
        <td><%= link_to 'Deletar', carro, class: "bt-red bt", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'cadastrar Carro', new_carro_path, class: "bt-green bt" %>

app/views/carros/new.html.erb
<h1>New Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Back', carros_path %>

app/views/carros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Placa:</strong>
  <%= @carro.placa %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @carro.modelo %>
</p>

<p>
  <strong>Chassi:</strong>
  <%= @carro.chassi %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @carro.ano %>
</p>

<%= link_to 'Edit', edit_carro_path(@carro) %> |
<%= link_to 'Back', carros_path %>